auth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from .views import (
    LoginView, LogoutView,
    UserListView, UserCreateView, UserUpdateView, UserDeleteView, UserDetailView,
    UserBlockView, UserUnblockView, UserChangePasswordView, USER_URL_PK
)


login_urls =  patterns(
    '',
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
)

users_manage_patterns = patterns(
    '',
    url(r'^$', UserListView.as_view(), name='list'),
    url(r'^/(?P<%s>\d+)/$' % USER_URL_PK, UserDetailView.as_view(), name='detail'),
    url(r'^/(?P<%s>\d+)/block/$' % USER_URL_PK, UserBlockView.as_view(), name='block'),
    url(r'^/(?P<%s>\d+)/unblock/$' % USER_URL_PK, UserUnblockView.as_view(), name='unblock'),
    url(r'^/add/$', UserCreateView.as_view(), name='add'),
    url(r'^/(?P<%s>\d+)/edit/$' % USER_URL_PK, UserUpdateView.as_view(), name='edit'),
    url(r'^/(?P<%s>\d+)/delete/$' % USER_URL_PK, UserDeleteView.as_view(), name='delete'),
    url(r'^/(?P<%s>\d+)/change-password/$' % USER_URL_PK, UserChangePasswordView.as_view(), name='change-password'),
    )


urlpatterns = patterns(
    '',
    url(r'^users', include(users_manage_patterns, namespace='users')),
    url(r'', include(login_urls)),
    # url(r'^files', include(files_urls, namespace='files')),
    # url(r'^users_files', include(users_files_urls, namespace='users_files')),
    )

demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.auth.views import login
from django.shortcuts import redirect
from views import AuthTemplateView
# Uncomment the next two lines to enable the admin:

from django.contrib import admin
admin.autodiscover()

# urlpatterns = patterns('',
#     url(r'^$', lambda request: redirect('/auth/login')),
# )

urlpatterns = patterns('',
                       url(r'^$', AuthTemplateView.as_view(
                           template_name='welcome.html'), name='welcome'),
                       )

urlpatterns += patterns('',
                        url(r'^admin/', include(admin.site.urls)),
                        )

if 'angular_rest_bookmarks' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^bookmarks/', include('angular_rest_bookmarks.urls',
                                                        namespace='rest_bookmarks')),
                            )

if 'my_auth' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^auth/',
                                include('my_auth.urls', namespace='auth')),
                            )


if 'my_files_storage' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^my_files_storage/', include('my_files_storage.urls',
                                                               namespace='my_files_storage')),
                            )

if 'my_calculator' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^my_calculator/', include('my_calculator.urls',
                                                            namespace='my_calculator')),
                            )

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += patterns('',
                            url(r'^(?P<path>favicon\..*)$', serve,
                                {'document_root': settings.STATIC_ROOT}),
                            url(r'^%s(?P<path>.*)$' %
                                settings.MEDIA_URL[1:], serve, {'document_root': settings.MEDIA_ROOT}),
                            url(r'^%s(?P<path>.*)$' %
                                settings.STATIC_URL[1:], 'django.contrib.staticfiles.views.serve', dict(insecure=True)),
                            )

micro_shop/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from django.conf import settings
from .views import SimpleStaticView, AuthTemplateView, ImportMailingView, MailingStatusView


urlpatterns = patterns('',
                       url(r'^api/',
                           include('notifications.api.urls', namespace='api')),
                       url(r'^import_mailing$', ImportMailingView.as_view(), name='import_mailing'),
                       url(r'^mailing_status/(?P<pk>\d+)$', MailingStatusView.as_view(), name='mailing_status'),
                       # url(r'^users_photos$', AuthTemplateView.as_view(
                       #     template_name='users_photos.html',), name='users_photos')
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^(?P<template_name>\w+)$',
                                SimpleStaticView.as_view(), name='example'),
                            )

my_calculator/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import TemplateView
from django.conf.urls import patterns, include, url
from django.conf import settings
from .views import SimpleStaticView, AuthTemplateView

handler404 = ''

urlpatterns = patterns('',
                       url(r'^api/',
                           include('my_calculator.api.urls', namespace='api')),
                       url(r'^calculator_form$', AuthTemplateView.as_view(
                           template_name='calculator_form.html'), name='calc')
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^(?P<template_name>\w+)$',
                                SimpleStaticView.as_view(), name='example'),
                            )

my_files_storage/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from django.conf import settings
from .views import SimpleStaticView, AuthTemplateView


urlpatterns = patterns('',
                       url(r'^api/',
                           include('my_files_storage.api.urls', namespace='api')),
                       url(r'^users_files$', AuthTemplateView.as_view(
                           template_name='users_files.html',), name='users_files'),
                       url(r'^users_photos$', AuthTemplateView.as_view(
                           template_name='users_photos.html',), name='users_photos')
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^(?P<template_name>\w+)$',
                                SimpleStaticView.as_view(), name='example'),
                            )

demo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import TemplateView
from django.conf import settings
try:
    from my_auth.views.mixins import AccessMixin
except ImportError:
    AccessMixin = object


class SimpleStaticView(AccessMixin, TemplateView):

    def get_template_names(self):
        return [self.kwargs.get('template_name') + '.html']

class AuthTemplateView(AccessMixin, TemplateView):
    pass

demo/templates/welcome.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Заготовка к закладкам</title>

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css"
          href="{% static 'angular-bookmarks/lib/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'angular-bookmarks/lib/bootstrap/dist/css/bootstrap-theme.css' %}">

</head>


<body>
<div class="container">
    <nav role="navigation" class="navbar navbar-default">
{# TODO: добавить менеджеры контекста чтобы проверять наличие приложений#}
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Корень</a></li>
                <li><a href="{% url 'my_calculator:calc'%}">Калькулятор</a></li>
                <li><a href="{% url 'rest_bookmarks:example'%}">Закладки</a></li>
                <li><a href="{% url 'my_files_storage:users_files'%}">Файлы</a></li>
                <li><a href="{% url 'my_files_storage:users_photos'%}">Фото</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
            </ul>
        </div>
    </nav>
</div>
<div class="container">
    <p>
        -----------------------------------------------------------------------------------------------------------------------
        <br>
        Задача калькулятор:
        Требуется:

        Реализовать веб-приложение Калькулятор.
        Калькулятор уровня стандартного.
        Верстка и дизайн не требуется. только рабочий интерфейс.
        Вся логика и валидация ввода выполняются на сервере, на фронтэнде только ввод и AJAX (отправка на сервер и отображение результата)

        Ввод осуществяется кликами мышкой по кнопкам на интерфейсе.

        Примерный интерфейс:

        [ 0 ]
        [ /] [ *] [ -] [ C]
        [ 7] [ 8] [ 9] [ -]
        [ 4] [ 5] [ 6] [ +]
        [ 1] [ 2] [ 3] [ =]
        [ 0] [ ,]

        Минимальные требования:

        Django=1.7
        django-rest-framework
    </p>
    <p>
        ------------------------------------------------------------------------------------------------------------------------
        <br>
        Задача закладки:
        Сделать закладки по аналогии google chrome. Для возможности просмотра на других устройствах.

        Минимальные требования:

        Django
        django-rest-framework
        angular
    </p>
    <p>
        ------------------------------------------------------------------------------------------------------------------------
        <br>
        Задача файлохранилище:

        Дизайн и внешний вид не важен, главное - архитектура и код.

        На главной странице есть возможность регистрации или авторизации в сервисе.

        После авторизации пользователь попадает в личный кабинет в котором отображаются его файлы в виде списка.

        Доступные операции с файлами:

            Добавление новых файлов;

            Скачивание существующих файлов;

            Удаление файлов


        Ограничение: У пользователя может быть не более 100 файлов.

        Директории и древовидная структура в файловом хранилище не поддерживаются.

        При скачивании генерируются ссылки без авторизации.

        При загрузке файлов должен использоваться механизм дедупликации хранящихся файлов. Если у кого либо из пользователей уже существует загружаемый файл, то дубль этого файла в системе не создается. Но в списке файлов пользователя этот файл появляется под тем именем, под котором он был залит, но при этом он ссылается на один и тот же физический оригинал.

        Use case

            Пользователь A обладает файлом test.bin который отображается у него в файловом хранилище

            Пользователь B пытается загрузить macro.txt который является полной копией test.bin

            Пользователю B выдается сообщение о том что загружаемый файл является дублем ( указывается где находится оригинал - у юзера такого то с таким то именем уже есть этот файл ), в файловом хранилище B появляется файл macro.txt ( который физически ссылается на test.bin ).

            Пользователь A удаляет файл test.bin, при этом в файловом хранилище B файл macro.txt остается и ссылка на него работает.


        Результат

            Развернутый в интернете для тестирования сервис и ссылка на него

            Присланный код
    </p>
    <p>
        ------------------------------------------------------------------------------------------------------------------------
        <br>
        Тестовое задание:

            Необходимо создать небольшое веб приложение, используя любой веб фреймворк (желательно тот, который Вы лучше всего знаете). Верстка не важна, уделяйте основное внимание бэкенду, оформлению кода, мелочам.

            Фактически приложение должно состоять из одной страницы, но по желанию можно разделить на несколько (отдельно форму загрузки).
            Необходимые элементы - форма загрузки фотографии и таблица со списком загруженных фото. Авторизация не обязательна.

        Форма загрузки:

            Текстовое поле для ввода названия фото
            Выбор файла


        Таблица:

            Превью фото (необходимо сделать уменьшенную копию фото (миниатюру); также данное превью должно являться ссылкой на оригинальное/полное изображение, которое открывается по клику на превью)
            Название фото (которое пользователь указывает при загрузке)
            Производитель и модель камеры (из EXIF, если присутствует)
            Размер файла
            Дата создания фото (из EXIF)
            Дата загрузки фото
            Кнопка удаления


        Требования:

            Не сохранять уже существующие фото. Проверять наличие дубликата файла и выдавать ошибку в случае обнаружения.
            Проверять является ли загружаемый файл изображением, если нет - выдавать ошибку. (Не использовать проверку наличия EXIF данных в качестве валидации)
            Не позволять сохранять фото, созданные более года назад (проверять дату создания фото из EXIF).
            Если отсутствует дата создания фото в EXIF, тогда следует выдать ошибку и не добавлять файл.


    </p>

</div>

<script src="{% static 'angular-bookmarks/lib/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'angular-bookmarks/lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>