auth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from .views import (
    LoginView, LogoutView,
    UserListView, UserCreateView, UserUpdateView, UserDeleteView, UserDetailView,
    UserBlockView, UserUnblockView, UserChangePasswordView, USER_URL_PK
)


login_urls =  patterns(
    '',
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
)

users_manage_patterns = patterns(
    '',
    url(r'^$', UserListView.as_view(), name='list'),
    url(r'^/(?P<%s>\d+)/$' % USER_URL_PK, UserDetailView.as_view(), name='detail'),
    url(r'^/(?P<%s>\d+)/block/$' % USER_URL_PK, UserBlockView.as_view(), name='block'),
    url(r'^/(?P<%s>\d+)/unblock/$' % USER_URL_PK, UserUnblockView.as_view(), name='unblock'),
    url(r'^/add/$', UserCreateView.as_view(), name='add'),
    url(r'^/(?P<%s>\d+)/edit/$' % USER_URL_PK, UserUpdateView.as_view(), name='edit'),
    url(r'^/(?P<%s>\d+)/delete/$' % USER_URL_PK, UserDeleteView.as_view(), name='delete'),
    url(r'^/(?P<%s>\d+)/change-password/$' % USER_URL_PK, UserChangePasswordView.as_view(), name='change-password'),
    )


urlpatterns = patterns(
    '',
    url(r'^users', include(users_manage_patterns, namespace='users')),
    url(r'', include(login_urls)),
    # url(r'^files', include(files_urls, namespace='files')),
    # url(r'^users_files', include(users_files_urls, namespace='users_files')),
    )

demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.auth.views import login
from django.shortcuts import redirect
from views import AuthTemplateView
# Uncomment the next two lines to enable the admin:

from django.contrib import admin
admin.autodiscover()

# urlpatterns = patterns('',
#     url(r'^$', lambda request: redirect('/auth/login')),
# )

urlpatterns = patterns('',
                       url(r'^$', AuthTemplateView.as_view(
                           template_name='welcome.html'), name='welcome'),
                       )

urlpatterns += patterns('',
                        url(r'^admin/', include(admin.site.urls)),
                        )

if 'angular_rest_bookmarks' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^bookmarks/', include('angular_rest_bookmarks.urls',
                                                        namespace='rest_bookmarks')),
                            )

if 'my_auth' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^auth/',
                                include('my_auth.urls', namespace='auth')),
                            )


if 'my_files_storage' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^my_files_storage/', include('my_files_storage.urls',
                                                               namespace='my_files_storage')),
                            )

if 'my_calculator' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^my_calculator/', include('my_calculator.urls',
                                                            namespace='my_calculator')),
                            )

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += patterns('',
                            url(r'^(?P<path>favicon\..*)$', serve,
                                {'document_root': settings.STATIC_ROOT}),
                            url(r'^%s(?P<path>.*)$' %
                                settings.MEDIA_URL[1:], serve, {'document_root': settings.MEDIA_ROOT}),
                            url(r'^%s(?P<path>.*)$' %
                                settings.STATIC_URL[1:], 'django.contrib.staticfiles.views.serve', dict(insecure=True)),
                            )

micro_shop/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from .views import SendEmailDetailView, EmailsListAPIView, EmailDetailView, NotificationsListAPIView, NotificationDetailView



email_urls = patterns(
    '',
    url(r'^send_email/', SendEmailDetailView.as_view(
    ), name='send_email'),
    url(r'^$', EmailsListAPIView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', EmailDetailView.as_view(), name='detail'),
)

notifications_urls = patterns(
    '',
    url(r'^$', NotificationsListAPIView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', NotificationDetailView.as_view(), name='detail'),
)



urlpatterns = patterns(
    '',
    url(r'^emails/', include(email_urls, namespace='emails')),
    url(r'^notifications/', include(notifications_urls, namespace='notifications')),
)

micro_shop/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from django.conf import settings
from .views import SimpleStaticView, AuthTemplateView, ImportMailingView, MailingStatusView


urlpatterns = patterns('',
                       url(r'^api/',
                           include('notifications.api.urls', namespace='api')),
                       url(r'^import_mailing$', ImportMailingView.as_view(), name='import_mailing'),
                       url(r'^mailing_status/(?P<pk>\d+)$', MailingStatusView.as_view(), name='mailing_status'),
                       # url(r'^users_photos$', AuthTemplateView.as_view(
                       #     template_name='users_photos.html',), name='users_photos')
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^(?P<template_name>\w+)$',
                                SimpleStaticView.as_view(), name='example'),
                            )

micro_shop/api/views/email.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, division
import logging
from datetime import date

from rest_framework import generics
from django.contrib.auth.models import User

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.core.mail import EmailMultiAlternatives

from post_office import mail
from post_office.models import Email

#from ..serializers import MyLeksemmaSerializer, MyNumberSerializer
from ..serializers import EmailSerializer
from .mixin import AccessMixin


logger = logging.getLogger(__name__)

# todo: переделать в виде viewsets readonly


# class MyNumberListAPIView(generics.ListAPIView, AccessMixin):
#     queryset = [{'number': number[1]} for number in enumerate(xrange(0, 10))]
#     serializer_class = MyNumberSerializer
#     authentication_classes = (authentication.SessionAuthentication,)
#     permission_classes = (permissions.IsAuthenticated,)
#
#
# class MyLexemmeListAPIView(generics.ListAPIView,  AccessMixin):
#     queryset = [{'operation': r'.'}, {'operation': r'+'},
#                 {'operation': r'-'}, {'operation': r'*'}, {'operation': r'/'}, ]
#     serializer_class = MyLeksemmaSerializer
#     authentication_classes = (authentication.SessionAuthentication,)
#     permission_classes = (permissions.IsAuthenticated,)
#
#
# class MyResultDetailView(generics.RetrieveAPIView):
#     authentication_classes = (authentication.SessionAuthentication,)
#     permission_classes = (permissions.IsAuthenticated,)
#
#     def get(self, request, *args, **kwargs):
#         try:
#             return Response(eval(kwargs.get('operation')))
#         except (ZeroDivisionError, OverflowError, FloatingPointError), err:
#             return Response(str(err))
#         except Exception, err:
#             logger.error(str(err))
#             return Response(str(err))
#
#
# class WrongOperationView(generics.RetrieveAPIView):
#     authentication_classes = (authentication.SessionAuthentication,)
#     permission_classes = (permissions.IsAuthenticated,)
#     error = 'corrupted operation'
#
#     def get(self, request, *args, **kwargs):
#         return Response(self.error)


class SendEmailDetailView(generics.RetrieveAPIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        try:
          #  self.create_test()
          #  self.create_meta()
            # return Response(self.send_email())
            return Response(self.send_email_with_postmaster())
        except (ZeroDivisionError, OverflowError, FloatingPointError), err:
            return Response(str(err))
        except Exception, err:
            logger.error(str(err))
            return Response(str(err))

    def create_meta(self):
        from post_office.models import Email
        mail = Email.objects.first()
        print mail.from_email
        from notifications.models import EmailMeta
        meta = EmailMeta(email=mail)
        meta.save()

    def create_test(self):
        from notifications.models import Place, Restaurant, Waiter
        p1 = Place(name='Demon Dogs', address='944 W. Fullerton')
        p1.save()
        r = Restaurant(place=p1, serves_hot_dogs=True, serves_pizza=False)
        r.save()
        raise Exception(r)


    def send_email(self):
        #TODO: Заменить заглушку
        msg = EmailMultiAlternatives("Subject", "text body","chaotism@rambler.ru", ["chaotism@mail.ru"])
        msg.attach_alternative("<html>html body</html>", "text/html")
        msg.send()
        response = msg.mandrill_response
        return response

        mandrill_id = response['_id']

    def send_email_with_postmaster(self):
        email = mail.send(
            ['recipient1@example.com'],
            'from@example.com',
            subject='Welcome!',
            message='Welcome home, {{ name }}!',
            html_message='Welcome home, <b>{{ name }}</b>!',
            headers={'Reply-to': 'reply@example.com'},
            scheduled_time=date(2014, 1, 1),
            context={'name': 'Alice'},
        )
        # response = mail.mandrill_response[0]
        return email.status


class EmailsListAPIView(generics.ListAPIView, generics.CreateAPIView):
    queryset = Email.objects.all()
    serializer_class = EmailSerializer

    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)


class EmailDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Email.objects.all()
    serializer_class = EmailSerializer

    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

micro_shop/api/views/mixin.py
# coding: utf8
import json
from django.conf import settings
from django.http import HttpResponse, StreamingHttpResponse
if 'my_auth' in settings.INSTALLED_APPS:
    try:
        from my_auth.views.mixins import AccessMixin
    except ImportError:
        AccessMixin = object


class AjaxableResponseMixin(object):

    """Mixin to add AJAX support to a form.

    Must be used with an object-based FormView (e.g. CreateView)

    """

    def render_to_json_response(self, context, **response_kwargs):
        data = json.dumps(context)
        response_kwargs['content_type'] = 'application/json'
        return HttpResponse(data, **response_kwargs)

    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return self.render_to_json_response(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return self.render_to_json_response(data)
        else:
            return response

micro_shop/api/views/notification.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, division
import logging
from datetime import date

from rest_framework import generics
from django.contrib.auth.models import User

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.core.mail import EmailMultiAlternatives

from post_office import mail
from post_office.models import Email

from notifications.models import Notification

from ..serializers import EmailSerializer, NotificationSerializer
from .mixin import AccessMixin
from import_export.admin import ImportMixin

logger = logging.getLogger(__name__)

# todo: переделать в виде viewsets readonly


class NotificationsListAPIView(generics.ListAPIView, generics.CreateAPIView):
    queryset = Notification.objects.all()
    serializer_class = NotificationSerializer

    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def filter_queryset(self, queryset):
        return queryset.filter(from_user=self.request.user)


class NotificationDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Notification.objects.all()
    serializer_class = NotificationSerializer

    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def filter_queryset(self, queryset):
        return queryset.filter(from_user=self.request.user)

micro_shop/views/mixins.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import user_passes_test
from django.conf import settings
from django.contrib.auth.decorators import REDIRECT_FIELD_NAME, login_required

def roles_required(roles, raise_exception=False):
    def check_roles(user):
        if user.is_in_roles(roles):
            return True
        if raise_exception:
            raise PermissionDenied
        return False
    return user_passes_test(check_roles)


def is_active_required(raise_exception=False):
    def user_is_active(user):
        if user.is_active:
            return True
        if raise_exception:
            raise PermissionDenied
        return False
    return user_passes_test(user_is_active)


class LoginRequiredMixin(object):
    redirect_field_name = REDIRECT_FIELD_NAME
    login_url = settings.LOGIN_URL

    def dispatch(self, request, *args, **kwargs):
        return login_required(
            redirect_field_name=self.redirect_field_name,
            login_url=self.login_url)(super(LoginRequiredMixin, self).dispatch)(request, *args, **kwargs)


class IsActiveRequired(object):

    def dispatch(self, request, *args, **kwargs):
        return is_active_required(raise_exception=True)(super(IsActiveRequired, self).dispatch)(request, *args, **kwargs)

class AccessMixin(LoginRequiredMixin, IsActiveRequired):
    pass

micro_shop/templates/micro_shop/import_mailing.html
{% load i18n static %}
{% get_current_language as current_language %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block meta_title %}Отправить письма{% endblock %}</title>

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css"
          href="{% static 'notifications/lib/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'notifications/lib/bootstrap/dist/css/bootstrap-theme.css' %}">
</head>


<body>
 {% block content %}
<div class="container">
    <a href="{% url 'auth:logout' %}" class="btn btn-danger pull-right">Выйти</a>
    <table ng-cloak class="table-hover table-bordered col-md-12" style="text-align: center">
        <thead ng-init="load_user_files({{ request.user.id }})">
        <tr>
            <h2>
                Список созданных запросовя&nbsp;{{ request.user.username }}
            </h2>
        </tr>
        <tr>
            <td class="col-md-2">
                <h4>
                    id
                </h4>
            </td>
            <td class="col-md-4">
                <h4>
                    Дата отправления
                </h4>
            </td>
            <td class="col-md-4">
                <h4>
                    Имя файла
                </h4>
            </td>
        </tr>
        </thead>

        <tbody>

        {% with mailing_list as mailings %}
            {% for mailing in mailings %}
            <tr>
                <td>
                    <h5>
                        {{ mailing.id }}
                    </h5>
                </td>
                <td>
                    <h5>
                        {{ mailing.created }}
                    </h5>
                </td>
                <td>
                    <h5>
                        <a href="{%  url 'notifications:mailing_status' pk=mailing.pk %}" class="btn btn-lg btn-success btn-block">Статус {{ mailing.file.name }}</a>
                    </h5>
                </td>
            </tr>
            {% endfor %}
        {% endwith %}
        </tbody>
        <tfoot>
        </tfoot>
    </table>

    {% endblock %}

    <h2>Загрузите список email</h2>
    <form enctype="multipart/form-data" action="{#%  url 'input:task-create' type_source.code %#}" method="post">
        {% with form as f %}
            {{ f.as_p }}
        {% endwith %}
        {% csrf_token %}
    <button type="submit" class="btn  btn-success btn-block">Загрузить файл</button>
    </form>


</div>


{% block js %}
<!-- scripts -->
<!--[if IE 8]>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/es5-shim/3.4.0/es5-shim.min.js"></script>
<![endif]-->

<script src="{% static 'notifications/lib/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'notifications/lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'notifications/lib/lodash/lodash.min.js' %}"></script>
{% endblock %}

{% block extra_js %}
{% endblock %}

</body>
</html>

micro_shop/templates/micro_shop/mailing_status.html
{% load i18n static %}
{% get_current_language as current_language %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block meta_title %}Статус отпраки{% endblock %}</title>

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css"
          href="{% static 'notifications/lib/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'notifications/lib/bootstrap/dist/css/bootstrap-theme.css' %}">
</head>


<body>
 {% block content %}
<div class="container">
    <a href="{% url 'auth:logout' %}" class="btn btn-danger pull-right">Выйти</a>
    <table ng-cloak class="table-hover table-bordered col-md-12" style="text-align: center">
        <thead ng-init="load_user_files({{ request.user.id }})">
        <tr>
            <h2>
                Список отправленны сообщений из файла &nbsp; {{ mailing_list.file }} пользователя {{ request.user.username }}
            </h2>
        </tr>
        <tr>
            <td class="col-md-2">
                <h4>
                    id
                </h4>
            </td>
            <td class="col-md-4">
                <h4>
                    Дата отправления
                </h4>
            </td>
            <td class="col-md-4">
                <h4>
                    Имя файла
                </h4>
            </td>
        </tr>
        </thead>

        <tbody>

        {% with emails_meta as emails %}
            {% for email in emails %}
            <tr>
                <td>
                    <h5>
                        {{ email.id }}
                    </h5>
                </td>
                <td>
                    <h5>
                        {{ email.created }}
                    </h5>
                </td>
                <td>
                      <h5>
                        {{ email.file.name }}
                        <a href="{{ file.url }}" class="btn btn-lg btn-success btn-block">скачать</a>
                    </h5>
                </td>
            </tr>
            {% endfor %}
        {% endwith %}
        </tbody>
        <tfoot>
        </tfoot>
    </table>

    {% endblock %}



</div>


{% block js %}
<!-- scripts -->
<!--[if IE 8]>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/es5-shim/3.4.0/es5-shim.min.js"></script>
<![endif]-->

<script src="{% static 'notifications/lib/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'notifications/lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'notifications/lib/lodash/lodash.min.js' %}"></script>
{% endblock %}

{% block extra_js %}
{% endblock %}

</body>
</html>